package com.enterprise.investmentanalytics.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseSchemaFixer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseSchemaFixer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) throws Exception {
        // CLEANUP ORPHANED DATA (Fixes Foreign Key Constraint failures)
        System.out.println("--- DATABASE SCHEMA FIXER : CLEANING ORPHANS ---");
        runSafely("DELETE FROM portfolios WHERE user_id NOT IN (SELECT id FROM users)");
        runSafely("DELETE FROM transactions WHERE user_id NOT IN (SELECT id FROM users)");
        runSafely("DELETE FROM monthly_profit_history WHERE user_id NOT IN (SELECT id FROM users)");
        runSafely("DELETE FROM deposit_requests WHERE user_id NOT IN (SELECT id FROM users)");

        // Drop unique constraint on monthly_profit_history to allow high-frequency
        // payouts
        runSafely("ALTER TABLE monthly_profit_history DROP INDEX UKpk5ocieho0al40rnwbuq63ry");
        runSafely("DROP INDEX UKpk5ocieho0al40rnwbuq63ry ON monthly_profit_history");
        // Fix based on error log: Index has a '0' suffix
        runSafely("ALTER TABLE monthly_profit_history DROP INDEX UKpk5ocieho0al40rnwbuq63ry0");
        runSafely("DROP INDEX UKpk5ocieho0al40rnwbuq63ry0 ON monthly_profit_history");

        // Also drop user_id_UNIQUE if it exists (Common autogenerated name)
        runSafely("ALTER TABLE monthly_profit_history DROP INDEX user_id_UNIQUE");

        runSafely("ALTER TABLE monthly_profit_history DROP INDEX uk_monthly_profit_user_month_year"); // Try standard
                                                                                                      // name too

        // Run silently to fix schema issues if they exist
        runSafely(
                "ALTER TABLE transactions MODIFY COLUMN type ENUM('CREDIT', 'DEBIT', 'PROFIT', 'PAYOUT', 'DEPOSIT', 'WITHDRAWAL')");
        runSafely("ALTER TABLE users MODIFY COLUMN user_id VARCHAR(20) NULL");
        runSafely("ALTER TABLE users MODIFY COLUMN status VARCHAR(50) NOT NULL");
        runSafely("ALTER TABLE transactions DROP INDEX user_id_UNIQUE");
        runSafely("CREATE INDEX idx_transactions_user_id ON transactions(user_id)");

        // Fix status column lengths
        runSafely("ALTER TABLE deposit_requests MODIFY COLUMN status VARCHAR(20) NOT NULL");
        runSafely("ALTER TABLE withdrawal_requests MODIFY COLUMN status VARCHAR(20) NOT NULL");
        runSafely("ALTER TABLE payout_requests MODIFY COLUMN status VARCHAR(20) NOT NULL");

        // Drop potential constraints (Failures expected if not present)
        runSafely("ALTER TABLE portfolios DROP FOREIGN KEY FK9xt36kgm9cxsf79r2me0d9f6u");
        runSafely("ALTER TABLE transactions DROP FOREIGN KEY FKqwv7rmvc8va8rep7piikrojds");
        runSafely("ALTER TABLE monthly_profit_history DROP FOREIGN KEY FKnhe6u818qrp1q0iw27racb98j");
        runSafely("ALTER TABLE deposit_requests DROP FOREIGN KEY fk_deposit_user");

        // Fix Binary Columns
        runSafely("ALTER TABLE portfolios MODIFY COLUMN user_id BINARY(16) NOT NULL");
        runSafely("ALTER TABLE transactions MODIFY COLUMN user_id BINARY(16) NOT NULL");
        runSafely("ALTER TABLE deposit_requests MODIFY COLUMN user_id BINARY(16) NOT NULL");

        // Ensure monthly_profit_history.user_id is VARCHAR for readable SM000X format
        runSafely("ALTER TABLE monthly_profit_history MODIFY COLUMN user_id VARCHAR(20) NOT NULL");

        // Fix COMPOUNDING clients with 0% or NULL profit percentage
        // COMPOUNDING should have 3.6% monthly rate (52% annual through compounding)
        System.out.println("--- FIXING COMPOUNDING PROFIT RATES ---");
        runSafely(
                "UPDATE portfolios SET profit_percentage = 3.6 WHERE profit_mode = 'COMPOUNDING' AND (profit_percentage IS NULL OR profit_percentage = 0)");
    }

    private void runSafely(String sql) {
        try {
            jdbcTemplate.execute(sql);
            System.out.println("Executed: " + sql);
        } catch (Exception e) {
            System.out.println("Failed to execute: " + sql + " Error: " + e.getMessage());
        }
    }
}
